language: android
android:
  components:
    - platform-tools
    - build-tools-23.0.1
    - android-23
    
before_script:
    - chmod +x gradlew
    
script: 
 - cd MAGPIE/  
 - ./gradlew build connectedCheck --info
